-- Database:    sr
-- Table:       organization_status
-- Description: Status of an organization within the platform

DROP TABLE IF EXISTS sr."organization_status";

CREATE TABLE IF NOT EXISTS sr."organization_status" (
    organization_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    organization_status_name VARCHAR(50) NOT NULL,
    organization_status_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (organization_status_id)
);

INSERT INTO sr."organization_status" ( 
    organization_status_name, organization_status_description
) VALUES
    ('Active','Organization is active'),
    ('Inactive','Organization is inactive'),
    ('Hold','Organization is on hold')
;

ALTER TABLE sr."organization_status" OWNER TO sradmin;
GRANT ALL ON TABLE sr."organization_status" TO sradmin;


