-- Database:    sr
-- Table:       organization_invitation_status
-- Description: Status of an invitation to join the Organization

DROP TABLE IF EXISTS sr."organization_invitation_status";

CREATE TABLE IF NOT EXISTS sr."organization_invitation_status" (
    organization_invitation_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    organization_invitation_status_name VARCHAR(50) NOT NULL,
    organization_invitation_status_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (organization_invitation_status_id)
);

INSERT INTO sr."organization_invitation_status" ( 
    organization_invitation_status_name, organization_invitation_status_description
) VALUES
    ('Ready','Invitation ready to be claimed'),
    ('Send Success','Invitation successfully sent to recipient'),
    ('Send Failure','Invitation failed to send to recipient'),
    ('Claimed','Invitation has been successfully claimed'),
    ('Expired','Invitation has expired'),
    ('Hold','Invitation is on hold'),
    ('Invalidated','Invitation is invalidated')
;

ALTER TABLE sr."organization_invitation_status" OWNER TO sradmin;
GRANT ALL ON TABLE sr."organization_invitation_status" TO sradmin;
