-- Database:    sr
-- Table:       user_role
-- Description: Roles and grants for organization users

DROP TABLE IF EXISTS sr."user_role";

CREATE TABLE IF NOT EXISTS sr."user_role" (
    user_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_role_name VARCHAR(50) NOT NULL,
    user_role_description VARCHAR(512),
    user_role_grants JSONB NULL,
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (user_role_id)
);

INSERT INTO sr."user_role" ( 
    user_role_name,
    user_role_description,
    user_role_grants
) VALUES
    ('Standard', 'Standard user',
        '{
            "ui": true,
            "zoom": true,
            "resources_read": true,
            "resources_write": false,
            "organization_read": true,
            "organization_write": false,
            "event_read": true,
            "event_write": false,
            "team_read": true,
            "team_write": false
        }'
    ),
    ('Admin', 'Organization administrator',
        '{
            "ui": true,
            "zoom": true,
            "resources_read": true,
            "resources_write": true,
            "organization_read": true,
            "organization_write": false,
            "event_read": true,
            "event_write": true,
            "team_read": true,
            "team_write": true
        }'
    ),
    ('Owner', 'Organization owner',
        '{
            "ui": true,
            "zoom": true,
            "resources_read": true,
            "resources_write": true,
            "organization_read": true,
            "organization_write": true,
            "event_read": true,
            "event_write": true,
            "team_read": true,
            "team_write": true
        }'
    );
ALTER TABLE sr."user_role" OWNER TO sradmin;
GRANT ALL ON TABLE sr."user_role" TO sradmin;
