-- Database:    sr
-- Table:       event_status
-- Description: Status types and details for an event

DROP TABLE IF EXISTS sr."event_status";

CREATE TABLE IF NOT EXISTS sr."event_status" (
    event_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    event_status_name VARCHAR(50) NOT NULL,
    event_status_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (event_status_id)
);

-- Do this first so we can reset the counter after

INSERT INTO sr."event_status" ( 
    event_status_id, event_status_name, event_status_description
) VALUES
    (999, 'Archived','Event is archived')
;

-- Now we can add the rows which will start from 1
INSERT INTO sr."event_status" ( 
    event_status_id, event_status_name, event_status_description
) VALUES
    (1, 'Not Ready','Event is not ready'),
    (2, 'Ready','Event is ready'),
    (3, 'Running','Event is underway'),
    (4, 'Judging','Event is being judged'),
    (5, 'Hold','Event is on hold'),
    (6, 'Complete','Event is complete')
;

-- Reset the sequence so we do not start from 1000
SELECT
    nextval('sr.event_status_event_status_id_seq')
AS
    next_value,
    last_value
FROM sr.event_status_event_status_id_seq;

SELECT setval('sr.event_status_event_status_id_seq', 6);

ALTER TABLE sr."event_status" OWNER TO sradmin;
GRANT ALL ON TABLE sr."event_status" TO sradmin;
