-- Database:    sr
-- Table:       event_type
-- Description: Event types and details for an event

DROP TABLE IF EXISTS sr."event_type";

CREATE TABLE IF NOT EXISTS sr."event_type" (
    event_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    event_type_name VARCHAR(50) NOT NULL,
    event_type_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (event_type_id)
);

INSERT INTO sr."event_type" ( 
    event_type_name, event_type_description
) VALUES
    ('Standard Hackathon','Standard hackathon event')
;

ALTER TABLE sr."event_type" OWNER TO sradmin;
GRANT ALL ON TABLE sr."event_type" TO sradmin;
