-- Database:    sr
-- Table:       event_team_form_mode
-- Description: Team formation mode options for Events

DROP TABLE IF EXISTS sr."event_team_form_mode";

CREATE TABLE IF NOT EXISTS sr."event_team_form_mode" (
    event_team_form_mode_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    event_team_form_mode_name VARCHAR(50) NOT NULL,
    event_team_form_mode_description VARCHAR(512),
    event_team_form_mode_enabled BOOLEAN NOT NULL DEFAULT(TRUE),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (event_team_form_mode_id)
);

INSERT INTO sr."event_team_form_mode" ( 
    event_team_form_mode_name, event_team_form_mode_description, event_team_form_mode_enabled
) VALUES
    ('Manual','Teams are formed manually by an Event administrator',TRUE),
    ('Automatic','Teams are formed automatically once an Event starts',TRUE),
    ('Free Agency','Teams are formed by Team Captains from a pool of available Free Agents',FALSE),
    ('Franchisor','Participants create their own Teams or choose to join an existing Team',TRUE);
;

ALTER TABLE sr."event_team_form_mode" OWNER TO sradmin;
GRANT ALL ON TABLE sr."event_team_form_mode" TO sradmin;
