-- Database:    sr
-- Table:       participant_role
-- Description: Participant roles and grants

DROP TABLE IF EXISTS sr."participant_role";

CREATE TABLE IF NOT EXISTS sr."participant_role" (
    participant_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    participant_role_name VARCHAR(50) NOT NULL,
    participant_role_description VARCHAR(512),
    participant_role_grants JSONB NULL,
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (participant_role_id)
);

INSERT INTO sr."participant_role" ( 
    participant_role_name,
    participant_role_description,
    participant_role_grants
) VALUES
    ('Spectator','Event spectator',
        '{
            "manage": false,
            "spectate": true,
            "play": false,
            "judge": false
        }'
    ),
    ('Player','Event player',
        '{
            "manage": false,
            "spectate": true,
            "play": true,
            "judge": false
        }'
    ),
    ('SME','Subject matter expert',
        '{
            "manage": false,
            "spectate": true,
            "play": false,
            "judge": false
        }'
    ),
    ('Judge','Event judge',
        '{
            "manage": false,
            "spectate": true,
            "play": false,
            "judge": true
        }'
    ),
    ('Manager','Event manager',
        '{
            "manage": true,
            "spectate": true,
            "play": false,
            "judge": false
        }'
    );

ALTER TABLE sr."participant_role" OWNER TO sradmin;
GRANT ALL ON TABLE sr."participant_role" TO sradmin;
