-- Database:    sr
-- Table:       team_status
-- Description: Status types and details for a team

DROP TABLE IF EXISTS sr."team_status";

CREATE TABLE IF NOT EXISTS sr."team_status" (
    team_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    team_status_name VARCHAR(50) NOT NULL,
    team_status_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (team_status_id)
);

INSERT INTO sr."team_status" ( 
    team_status_name, team_status_description
) VALUES
    ('Not Ready','Team is not ready'),
    ('Ready','Team is ready'),
    ('Hold','Team is on hold'),
    ('Archived','Team is archived')
;

ALTER TABLE sr."team_status" OWNER TO sradmin;
GRANT ALL ON TABLE sr."team_status" TO sradmin;


