-- Database:    sr
-- Table:       team_member_role
-- Description: Team member roles and grants

DROP TABLE IF EXISTS sr."team_member_role";

CREATE TABLE IF NOT EXISTS sr."team_member_role" (
    team_member_role_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    team_member_role_name VARCHAR(50) NOT NULL,
    team_member_role_description VARCHAR(512),
    grant_team_play BOOLEAN DEFAULT(false),
    grant_team_management BOOLEAN DEFAULT(false),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (team_member_role_id)
);

INSERT INTO sr."team_member_role" ( 
    team_member_role_name,
    team_member_role_description,
    grant_team_play,
    grant_team_management
) VALUES
    ('Player','Team player', TRUE, FALSE),
    ('Leader','Team leader', TRUE, TRUE)
;

ALTER TABLE sr."team_member_role" OWNER TO sradmin;
GRANT ALL ON TABLE sr."team_member_role" TO sradmin;
