-- Database:    sr
-- Table:       cloud_account_provider
-- Description: Cloud provider details

DROP TABLE IF EXISTS sr."cloud_account_provider";

CREATE TABLE IF NOT EXISTS sr."cloud_account_provider" (
    cloud_account_provider_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cloud_account_provider_name VARCHAR(25) NOT NULL,
    cloud_account_provider_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (cloud_account_provider_id)
);

INSERT INTO sr."cloud_account_provider" ( 
    cloud_account_provider_name, cloud_account_provider_description
) VALUES
    ('AWS','Amazon Web Services'),
    ('GCP','Google Cloud Platform'),
    ('Azure','Microsoft Azure')
;

ALTER TABLE sr."cloud_account_provider" OWNER TO sradmin;
GRANT ALL ON TABLE sr."cloud_account_provider" TO sradmin;
