-- Database:    sr
-- Table:       cloud_account_status
-- Description: Status of cloud accounts

DROP TABLE IF EXISTS sr."cloud_account_status";

CREATE TABLE IF NOT EXISTS sr."cloud_account_status" (
    cloud_account_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cloud_account_status_name VARCHAR(50) NOT NULL,
    cloud_account_status_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (cloud_account_status_id)
);

INSERT INTO sr."cloud_account_status" ( 
    cloud_account_status_name, cloud_account_status_description
) VALUES
    ('Ready','Cloud account is ready for use'),
    ('Clean','Cloud account is clean of all resources'),
    ('Inactive','Cloud account is inactive'),
    ('In Use','Cloud account is currently in use'),
    ('Hold','Cloud account is on hold')
;

INSERT INTO sr."cloud_account_status" ( 
    cloud_account_status_id, cloud_account_status_name, cloud_account_status_description
) VALUES
    (999, 'Archived','Cloud account is archived')
;


ALTER TABLE sr."cloud_account_status" OWNER TO sradmin;
GRANT ALL ON TABLE sr."cloud_account_status" TO sradmin;


