-- Database:    sr
-- Table:       cloud_account_access_level
-- Description: Cloud Account access levels

DROP TABLE IF EXISTS sr."cloud_account_access_level";

CREATE TABLE IF NOT EXISTS sr."cloud_account_access_level" (
    cloud_account_access_level_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cloud_account_access_level_name VARCHAR(50) NOT NULL,
    cloud_account_access_level_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (cloud_account_access_level_id)
);

INSERT INTO sr."cloud_account_access_level" ( 
    cloud_account_access_level_name,
    cloud_account_access_level_description
) VALUES
    ('ReadOnly','Read-only access'),
    ('PowerUser','Power User access'),
    ('Administrator','Administrator access')
;

ALTER TABLE sr."cloud_account_access_level" OWNER TO sradmin;
GRANT ALL ON TABLE sr."cloud_account_access_level" TO sradmin;
