-- Database:    sr
-- Table:       coin_transaction_status
-- Description: Status types and details for a Coin Transaction

DROP TABLE IF EXISTS sr."coin_transaction_status";

CREATE TABLE IF NOT EXISTS sr."coin_transaction_status" (
    transaction_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    transaction_status_name VARCHAR(50) NOT NULL,
    transaction_status_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (transaction_status_id)
);

INSERT INTO sr."coin_transaction_status" ( 
    transaction_status_name, transaction_status_description
) VALUES
    ('Not executed','Transaction was not executed'),
    ('Executed','Transaction successfully executed'),
    ('Failed','Tranaction execution failed')
;

ALTER TABLE sr."coin_transaction_status" OWNER TO sradmin;
GRANT ALL ON TABLE sr."coin_transaction_status" TO sradmin;
