-- Database:    sr
-- Table:       judging_criterion_status
-- Description: Status types and details for a judging criterion

DROP TABLE IF EXISTS sr."judging_criterion_status";

CREATE TABLE IF NOT EXISTS sr."judging_criterion_status" (
    judging_criterion_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    judging_criterion_status_name VARCHAR(50) NOT NULL,
    judging_criterion_status_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (judging_criterion_status_id)
);

INSERT INTO sr."judging_criterion_status" ( 
    judging_criterion_status_name, judging_criterion_status_description
) VALUES
    ('Available','Criterion is available for use'),
    ('Unavailable','Criterion is unavailable for use'),
    ('Archived','Criterion is archived')
;

ALTER TABLE sr."judging_criterion_status" OWNER TO sradmin;
GRANT ALL ON TABLE sr."judging_criterion_status" TO sradmin;
