-- Database:    sr
-- Table:       judging_criterion_category
-- Description: Category types and details for a judging criterion

DROP TABLE IF EXISTS sr."judging_criterion_category";

CREATE TABLE IF NOT EXISTS sr."judging_criterion_category" (
    judging_criterion_category_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    judging_criterion_category_name VARCHAR(50) NOT NULL,
    judging_criterion_category_icon VARCHAR(50),
    judging_criterion_category_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (judging_criterion_category_id)
);

INSERT INTO sr."judging_criterion_category" ( 
    judging_criterion_category_name,
    judging_criterion_category_icon,
    judging_criterion_category_description
) VALUES
    ('Other','other','Anything else not covered'),
    ('Performance','performance','How well did the solition perform'),
    ('Cost','cost','How cost-effective is the solution'),
    ('Feasibility','feasibility','How feaible is the solution'),
    ('Teamwork','teamwork','How well the team worked together'),
    ('Presentation','presentation','How well was the solution presented'),
    ('Innovation','innovation','How innovative is the solution')
;

ALTER TABLE sr."judging_criterion_category" OWNER TO sradmin;
GRANT ALL ON TABLE sr."judging_criterion_category" TO sradmin;
