-- Database:    sr
-- Table:       user_tag
-- Description: Tags that can be assigned to Users, Participants, Team Members

DROP TABLE IF EXISTS sr."user_tag";
ALTER SEQUENCE IF EXISTS sr."user_tag" RESTART WITH 1;

CREATE TABLE IF NOT EXISTS sr."user_tag" (
    user_tag_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    user_tag_name VARCHAR(50) NOT NULL,
    user_tag_category VARCHAR(50) NOT NULL,
    user_tag_type VARCHAR(50) NOT NULL,
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (user_tag_id)
);

INSERT INTO sr."user_tag" ( 
    user_tag_name,
    user_tag_category,
    user_tag_type
) VALUES
    ('angularjs', 'development', 'skill'),
    ('ansible', 'operations', 'skill'),
    ('apache webserver', 'operations', 'skill'),
    ('api gateway', 'operations', 'skill'),
    ('aws', 'operations', 'skill'),
    ('blockchain', 'development', 'skill'),
    ('c', 'development', 'skill'),
    ('c++', 'development', 'skill'),
    ('chef', 'operations', 'skill'),
    ('cicd', 'operations', 'skill'),
    ('css', 'development', 'skill'),
    ('docker', 'operations', 'skill'),
    ('django', 'development', 'skill'),
    ('dotnet', 'development', 'skill'),
    ('dynamodb', 'development', 'skill'),
    ('ec2', 'operations', 'skill'),
    ('elk', 'operations', 'skill'),
    ('elm', 'development', 'skill'),
    ('emr', 'operations', 'skill'),
    ('excel', 'presentation', 'skill'),
    ('go', 'development', 'skill'),
    ('git', 'operations', 'skill'),
    ('haproxy', 'operations', 'skill'),
    ('haskell', 'operations', 'skill'),
    ('iot', 'development', 'skill'),
    ('java', 'development', 'skill'),
    ('javascript', 'development', 'skill'),
    ('jira', 'operations', 'skill'),
    ('json', 'development', 'skill'),
    ('kafka', 'operations', 'skill'),
    ('kinesis', 'operations', 'skill'),
    ('kubernetes', 'operations', 'skill'),
    ('lambda functions', 'operations', 'skill'),
    ('lisp', 'development', 'skill'),
    ('lucid', 'presentation', 'skill'),
    ('machine learning', 'development', 'skill'),
    ('memcached', 'operations', 'skill'),
    ('mssql', 'operations', 'skill'),
    ('mysql', 'development', 'skill'),
    ('nextjs', 'development', 'skill'),
    ('nginx', 'operations', 'skill'),
    ('nodejs', 'development', 'skill'),
    ('nosql', 'development', 'skill'),
    ('perl', 'development', 'skill'),
    ('php', 'development', 'skill'),
    ('sradminql', 'development', 'skill'),
    ('powerpoint', 'presentation', 'skill'),
    ('prometheus', 'operations', 'skill'),
    ('puppet', 'operations', 'skill'),
    ('python', 'development', 'skill'),
    ('reactjs', 'development', 'skill'),
    ('rabbitmq', 'operations', 'skill'),
    ('redis', 'operations', 'skill'),
    ('redshift', 'development', 'skill'),
    ('rest apis', 'development', 'skill'),
    ('ruby', 'development', 'skill'),
    ('rust', 'development', 'skill'),
    ('terraform', 'operations', 'skill'),
    ('tomcat', 'operations', 'skill'),
    ('s3', 'operations', 'skill'),
    ('salt', 'operations', 'skill'),
    ('scala', 'development', 'skill'),
    ('shell scripting', 'operations', 'skill'),
    ('spark', 'development', 'skill'),
    ('sqs', 'operations', 'skill'),
    ('typescript', 'development', 'skill'),
    ('vue', 'development', 'skill'),
    ('yaml', 'development', 'skill');

ALTER TABLE sr."user_tag" OWNER TO sradmin;
GRANT ALL ON TABLE sr."user_tag" TO sradmin;
