-- Database:    sr
-- Table:       external_link_type
-- Description: Link types for external URL links

DROP TABLE IF EXISTS sr."external_link_type";

CREATE TABLE IF NOT EXISTS sr."external_link_type" (
    external_link_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    external_link_type_name VARCHAR(100) NOT NULL,
    external_link_type_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (external_link_type_id)
);

INSERT INTO sr."external_link_type" ( 
    external_link_type_name, external_link_type_description
) VALUES
    ('Other','Other link type'),
    ('SCM','Source Code Management repository'),
    ('Presentation','Presentation document'),
    ('Meeting','External meeting link'),
    ('Demonstration','Where a running version of the team project can be viewed'),
    ('Video','Video (YouTube, Vimeo, etc.)'),
    ('Documentation','Documentation for the team project'),
    ('Spotify Playlist', 'Spotify playlist')
;

ALTER TABLE sr."external_link_type" OWNER TO sradmin;
GRANT ALL ON TABLE sr."external_link_type" TO sradmin;


