-- Database:    sr
-- Table:       cloud_resource_type
-- Description: Types of resources in cloud accounts

DROP TABLE IF EXISTS sr."cloud_resource_type";

CREATE TABLE IF NOT EXISTS sr."cloud_resource_type" (
    cloud_resource_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    cloud_resource_type_name VARCHAR(100) NOT NULL,
    cloud_resource_type_description VARCHAR(512),
    cloud_account_provider_id INTEGER NOT NULL,
    stackcash_cost NUMERIC(7,2) NOT NULL DEFAULT(0.00),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (cloud_resource_type_id)
);

ALTER TABLE sr."cloud_resource_type" ADD CONSTRAINT fk_cloud_account_provider
    FOREIGN KEY(cloud_account_provider_id)
    REFERENCES sr.cloud_account_provider(cloud_account_provider_id);

INSERT INTO sr."cloud_resource_type" ( 
    cloud_resource_type_name, cloud_resource_type_description, stackcash_cost, cloud_account_provider_id
) VALUES
    (
        'aws.ec2',
        'AWS EC2 Instance',
        100.00,
        (
            SELECT
                cloud_account_provider_id
            FROM
                sr.cloud_account_provider
            WHERE
                cloud_account_provider_name = 'AWS'
        )
    )
;

ALTER TABLE sr."cloud_resource_type" OWNER TO sradmin;
GRANT ALL ON TABLE sr."cloud_resource_type" TO sradmin;
