-- Database:    sr
-- Table:       marketplace_item_type
-- Description: Types of marketplace items

DROP TABLE IF EXISTS sr."marketplace_item_type";

CREATE TABLE IF NOT EXISTS sr."marketplace_item_type" (
    marketplace_item_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    marketplace_item_type_name VARCHAR(100) NOT NULL,
    marketplace_item_type_description VARCHAR(512),
    stackcash_cost NUMERIC(7,2) NOT NULL DEFAULT(0.00),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (marketplace_item_type_id)
);

INSERT INTO sr."marketplace_item_type" ( 
    marketplace_item_type_name, marketplace_item_type_description, stackcash_cost
) VALUES
    (
        'Event',
        'StackRef Event',
        100.00
    )
;

-- Permissions

ALTER TABLE sr."marketplace_item_type" OWNER TO sradmin;
GRANT ALL ON TABLE sr."marketplace_item_type" TO sradmin;
