-- Database:    sr
-- Table:       marketplace_item
-- Description: Items an Organiation can purchase for and inside an Event

ALTER TABLE IF EXISTS sr."marketplace_item" DROP CONSTRAINT IF EXISTS fk_marketplace_item_type_id;
DROP TABLE IF EXISTS sr."marketplace_item";

CREATE TABLE IF NOT EXISTS sr."marketplace_item" (
    marketplace_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    marketplace_item_name VARCHAR(100) NOT NULL,
    marketplace_item_description VARCHAR(512),
    marketplace_item_type_id INT4 NOT NULL DEFAULT 1,
    stackcash_cost NUMERIC(7,2) NOT NULL DEFAULT(0.00),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (marketplace_item_id)
);

ALTER TABLE sr."marketplace_item" ADD CONSTRAINT fk_marketplace_item_type_id
    FOREIGN KEY (marketplace_item_type_id)
    REFERENCES sr.marketplace_item_type(marketplace_item_type_id);

INSERT INTO sr."marketplace_item" ( 
    marketplace_item_name, marketplace_item_description, marketplace_item_type_id, stackcash_cost
) VALUES
    (
        'Standard Hackathon',
        'Standard hackathon event',
        (
            SELECT
                marketplace_item_type_id
            FROM
                sr.marketplace_item_type
            WHERE
                marketplace_item_type_name = 'Event'
        ),
        100.00
    )
;

-- Permissions

ALTER TABLE sr."marketplace_item" OWNER TO sradmin;
GRANT ALL ON TABLE sr."marketplace_item" TO sradmin;
