-- Database:    sr
-- Table:       kanban_item_status
-- Description: Status types and details for a kanban item

DROP TABLE IF EXISTS sr."kanban_item_status";

CREATE TABLE IF NOT EXISTS sr."kanban_item_status" (
    kanban_item_status_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    kanban_item_status_name VARCHAR(50) NOT NULL,
    kanban_item_status_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (kanban_item_status_id)
);

INSERT INTO sr."kanban_item_status" ( 
    kanban_item_status_id, kanban_item_status_name, kanban_item_status_description
) VALUES
    (999, 'Archived','Kanban item is archived')
;


INSERT INTO sr."kanban_item_status" ( 
    kanban_item_status_id, kanban_item_status_name, kanban_item_status_description
) VALUES
    (1, 'To Do','Kanban item is marked To Do'),
    (2, 'In Progress','Kanban item is in progress'),
    (3, 'Done','Kanban item is completed')
;

SELECT
    nextval('sr.kanban_item_status_kanban_item_status_id_seq')
AS
    next_value,
    last_value
FROM sr.kanban_item_status_kanban_item_status_id_seq;

SELECT setval('sr.kanban_item_status_kanban_item_status_id_seq', 3);

ALTER TABLE sr."kanban_item_status" OWNER TO sradmin;
GRANT ALL ON TABLE sr."kanban_item_status" TO sradmin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sr."kanban_item_status" TO role_api;
