-- Database:    sr
-- Table:       entity_asset_type
-- Description: Type of entity asset in CDN

DROP TABLE IF EXISTS sr."entity_asset_type";

CREATE TABLE IF NOT EXISTS sr."entity_asset_type" (
    entity_asset_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    entity_asset_type_name VARCHAR(50) NOT NULL,
    entity_asset_type_description VARCHAR(512),
    ts_created TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    ts_modified TIMESTAMP WITHOUT TIME ZONE DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY (entity_asset_type_id)
);

INSERT INTO sr."entity_asset_type" ( 
    entity_asset_type_name, entity_asset_type_description
) VALUES
    ('unknown','Unknown file type'),
    ('banner_image','Entity banner image'),
    ('screenshot_image','Screenshot image'),
    ('avatar_image','Avatar image'),
    ('pdf','PDF file'),
    ('video','Video file'),
    ('audio','Audio file'),
    ('invitation_list', 'Organization invitation list'),
    ('spotify', 'Spotify playlist')
;

ALTER TABLE sr."entity_asset_type" OWNER TO sradmin;
GRANT ALL ON TABLE sr."entity_asset_type" TO sradmin;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE sr."entity_asset_type" TO role_api;
